### ISSUE TITLE
Bug in speed

### ISSUE THREAD

**Issue by mojtabahdpr** [risitt/kissStepper#2]
hi
i test your stepper library and i find a bug in setmaxspeed function ; when using micro step this function not change to micro step option and set for always in 200 step/rev ,
sorry for wordy,

**Comment by risitt** [comment]
Hi mojtabahdpr,

This is intentional. The speed and acceleration is set in full steps so that you can very easily calculate back and forth between revolutions per minute. If you change the microstepping mode, the motor will make more precise movements, but the speed will still be the same. Once set, speed and acceleration should not change, regardless of microstepping.

Can you describe the situation you have in which you need the speed to change in response to different microstepping modes?

**Comment by mojtabahdpr** [comment]
tanx risitt,
this is my cod
  when i set 1/16 micro step and for one rps or 60 rpm speed i set maxspeed to 200 step/s that is wrong and 200*16 step/s is true because i set 1/16 micro step.
another problem in your lib perhaps in my code when i change target position to another position whit serial port and moveto function motor have have a bit lag then go to another position .  

`
#include <kissStepper.h>
float ss;
float bb=200*16; one rev

/ 
kissStepper mot(
    kissPinAssignments(8,9),
    kissMicrostepConfig(MICROSTEP_16)
);
void setup()
{
    Serial.begin(9600);
   Serial.flush();
   Serial.setTimeout(100) ;

```
mot.begin(MICROSTEP_16);
mot.setAccel(0);
mot.setMaxSpeed(200); // 200 is ful step and not nessery product in 16 
```

}

void loop()
{

if (Serial.available())
    {

```
ss = Serial.parseFloat(); 

 Serial.print("ss = ");

 Serial.println(ss,DEC);      
}         

    mot.moveTo(bb*ss);
    mot.work();      
```

}  

`

**Comment by risitt** [comment]
The function argument for setMaxSpeed is **full steps** per second, not microsteps. This may not be clear in the API documentation, so I might need to change that.

setMaxSpeed (200) means "200 **full steps** per second"

So if your motor is 200 steps/rev, as many seem to be, then setMaxSpeed (200) is always 60 RPM, regardless of microstepping.

So, to restate, there are only two things which determine the speed of the motor. The number you put in setMaxSpeed(), and the number of physical steps (**full steps**) in the motor itself. Microstepping does not change either of these things.

Speed (RPM) = (maxSpeed / motor's steps per revolution) \* 60

All microstepping changes is position precision and the smoothness of movement.

Serial communication is slow and ties up the Arduino for a moment. That is probably the cause of the lag. You can attempt to use a higher baud rate to reduce the amount of lag. Higher baud rates are less reliable.

Another thing is, Arduinos are _very slow_ at floats. Using any floats, parseFloat, etc will slow down your program and make the sketch larger as well. So try to avoid floats. Use long ints for motor position. I know you want to set the position in fractions of a revolution, but that will make your program slower. Then again, maybe not noticeably since that float calculation should only occur once every time you send a number over serial. Try increasing the baud rate first. Maybe that's all you need to do.

**Comment by mojtabahdpr** [comment]
tanx risitt ,
i increase baud and lag now is solve .
i think your lib need a func for set target position when stepper is running.

**Comment by risitt** [comment]
My apologies for the insanely long delay in getting back to you, I've been "sidetracked" by university for a while now.

I will be revisiting this library in the near future and I'll see about adding that feature you've requested. For the time being you just have to use stop() followed by changing the target position.
